#!/usr/bin/env bash

# Pretty print XML (use `jq` for json):
alias xq="xmllint --format"

# Show local ip:
alias localip="ipconfig getifaddr en0"

# Prompt user if moving file to a location where a file of that name already exists
alias mv="mv -i"

# Run kubernetes commands with "k <command>"
alias k="kubectl"

# Replace ls with a modern lister (eza, fallback to exa)
if [ -x "$(command -v eza)" ]; then alias ls="eza -al"
elif [ -x "$(command -v exa)" ]; then alias ls="exa -al"; fi

LOCAL_ALIASES=~/.aliases_local
[ -f "$LOCAL_ALIASES" ] && source "$LOCAL_ALIASES"
